version: "2"

services:
  httpd-proxy:
    build: ./httpd-proxy/
    networks:
     - front
     - back
    ports:
     - "80:80"
     - "443:443"

  sp:
    build: ./sp/ 
    networks:
     - back

  idp:
    build: ./idp-webapp-overlay-docker
    expose:
      - "8443"
    ports:
      - "5000:5000"
    networks:
     - back
    volumes:
     - ~/.m2:/root/.m2

networks:
  front:
    driver: bridge
  back:    
    driver: bridge
